export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const ADD_MESSAGE = "ADD_MESSAGE";
export const MARK_MESSAGES_AS_READ = "MARK_MESSAGES_AS_READ";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const LOAD_MESSAGES = "LOAD_MESSAGES";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const ADD_CONVERSATION = "ADD_CONVERSATION";
export const REMOVE_CONVERSATION = "REMOVE_CONVERSATION";

export const CREATE_BOT = "CREATE_BOT";
export const DELETE_BOT = "DELETE_BOT";
export const UPDATE_BOT = "UPDATE_BOT";

export const CREATE_CHATBOX = "CREATE_CHATBOX";
export const UPDATE_CHATBOX_NAME = "UPDATE_CHATBOX_NAME";
export const DELETE_CHATBOX = "DELETE_CHATBOX";

export const ADD_CHAT = "ADD_CHAT";
export const SET_CONVERSATION_MESSAGES = "SET_CONVERSATION_MESSAGES";
export const CLEAR_CONVERSATION_OF_DELETED_CHATBOX = "CLEAR_CONVERSATION_MESSAGES";

export const CREATE_IFRAME_BOX = "CREATE_IFRAME_BOX";

export const SET_STREAM_AGENT_INFO = "SET_STREAM_AGENT_INFO";
export const SET_STREAM_MESSAGES = "SET_STREAM_MESSAGES";
export const ADD_STREAM_MESSAGE = "ADD_STREAM_MESSAGE";
export const UPDATE_STREAM_LATEST_MESSAGE = "UPDATE_STREAM_LATEST_MESSAGE";
export const SET_STREAM_CONVERSATION_INFO = "SET_STREAM_CONVERSATION_INFO";